# CREATE DATABASE TVShowsDatabase;
USE TVShowsDatabase;

# If tables need to be emptied and recreated, drop them in this order.

# DROP TABLE UserReviews;
# DROP TABLE ShowGenres;
# DROP TABLE TVShows;
# DROP TABLE Genres;
# DROP TABLE Users;

# Creates necessary tables for database. KEEP THIS ORDER.
CREATE TABLE Users(
UserId INT NOT NULL AUTO_INCREMENT,
UserName VARCHAR(64) NOT NULL UNIQUE,
UserPassword VARCHAR(100) NOT NULL,
NumOfReviews INT DEFAULT 0,
PRIMARY KEY ( UserId )
);

CREATE TABLE Genres(
GenreID INT AUTO_INCREMENT,
Genre VARCHAR(32),
PRIMARY KEY ( GenreID )
);

CREATE TABLE TVShows(
ShowId INT NOT NULL AUTO_INCREMENT,
ShowName VARCHAR(100) NOT NULL,
ShowDesc VARCHAR(10000) NOT NULL,
NumSeasons INT NOT NULL,
NumEpisodes INT NOT NULL,
EpisodeLength INT NOT NULL,
YearReleased INT NOT NULL,
Ongoing BOOL NOT NULL,
RTrating DOUBLE NOT NULL,
IMDBrating DOUBLE NOT NULL,
AVGUserRating DOUBLE NOT NULL,
PRIMARY KEY ( ShowId )
);

CREATE TABLE ShowGenres(
ShowId INT NOT NULL,
GenreId INT NOT NULL,
PRIMARY KEY ( ShowId, GenreId ),
CONSTRAINT FK_Genre FOREIGN KEY (GenreId)
REFERENCES Genres(GenreId) ON DELETE CASCADE,
CONSTRAINT FK_Show FOREIGN KEY(ShowId)
REFERENCES TVShows(ShowId) ON DELETE CASCADE
);

CREATE TABLE UserReviews(
ReviewId INT AUTO_INCREMENT,
ShowId INT NOT NULL,
UserId INT NOT NULL,
UserRating DOUBLE DEFAULT 0,
UserComment VARCHAR(1000),
PRIMARY KEY ( ReviewId ),
CONSTRAINT Review UNIQUE ( ShowId, UserId ),
CONSTRAINT FK_ShowReview FOREIGN KEY (ShowId)
REFERENCES TVShows(ShowId) ON DELETE CASCADE,
CONSTRAINT FK_UserReview FOREIGN KEY (UserId)
REFERENCES Users(UserId) ON DELETE CASCADE
);

#LOAD DATA LOCAL INFILE '{DIRECTORY}/TVShows.csv' 
#INTO TABLE TVShows FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' ignore 1 lines;